image:
  file: .gitpod.Dockerfile
tasks:
- init: |
    echo "export OUTSIDE_COLLABORATORS_GITHUB_ORG=icub-tech-iit" >> ~/.bashrc-custom
    echo "export OUTSIDE_COLLABORATORS_METADATA_FILENAME=.outside-collaborators/override.yml" >> ~/.bashrc-custom
    echo "source ~/.bashrc-custom" >> ~/.bashrc
    source ~/.bashrc-custom
