name: Create Mentioning Comment

on:
  repository_dispatch:
    types: [create_mentioning_comment]

jobs:
  create:
    name: "Create"
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo gem install octokit yaml
      - name: Set Env Variables
        run: |
          echo "OUTSIDE_COLLABORATORS_GITHUB_REPO=${{ github.event.client_payload.repo }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_EVENT_NAME=${{ github.event.client_payload.event_name }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_ISSUE_NUMBER=${{ github.event.client_payload.issue_number }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_PR_NUMBER=${{ github.event.client_payload.pr_number }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_COMMENT_ID=${{ github.event.client_payload.comment_id }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_TOKEN=${{ secrets.OUTSIDE_COLLABORATORS_TOKEN_BOT }}" >> ${GITHUB_ENV}
      - uses: actions/checkout@master
      - name: Run Handler
        run: |
          cd scripts
          ./mentioning-comment-handler.rb
