name: List Automated Repositories

on:
  pull_request_target:
    branches:
    - 'master'
    paths:
    - "groups/*.yml"
    - "groups/*.yaml"
  workflow_dispatch:

jobs:
  Update:
    name: "List"
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo gem install octokit yaml
      - name: Set Env Variables
        run: |
          echo "::set-env name=OUTSIDE_COLLABORATORS_GITHUB_ORG::${{ github.repository_owner }}"
          echo "::set-env name=OUTSIDE_COLLABORATORS_METADATA_FILENAME::.outside-collaborators/override.yml"
          echo "::set-env name=OUTSIDE_COLLABORATORS_GITHUB_TOKEN::${{ secrets.OUTSIDE_COLLABORATORS_TOKEN_BOT }}"
      - uses: actions/checkout@master
      - name: Run Handler
        run: |
          cd scripts
          ./list-automated-repositories.rb
      
